In [2]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('old_gen_wdup.csv', index_col = None)

In [34]:
df = df.drop("Unnamed: 0", axis = 1)

In [35]:
df

,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
0,1,Bulbasaur,Grass Poison,318.0,45.0,49.0,49.0,65.0,65.0,45.0
1,2,Ivysaur,Grass Poison,405.0,60.0,62.0,63.0,80.0,80.0,60.0
2,3,Venusaur,Grass Poison,525.0,80.0,82.0,83.0,100.0,100.0,80.0
3,3,Venusaur Mega Venusaur,Grass Poison,625.0,80.0,100.0,123.0,122.0,120.0,80.0
4,4,Charmander,Fire,309.0,39.0,52.0,43.0,60.0,50.0,65.0
...,...,...,...,...,...,...,...,...,...,...
582,490,Manaphy,Water,600.0,100.0,100.0,100.0,100.0,100.0,100.0
583,491,Darkrai,Dark,600.0,70.0,90.0,90.0,135.0,90.0,125.0
584,492,Shaymin Land Forme,Grass,600.0,100.0,100.0,100.0,100.0,100.0,100.0
585,492,Shaymin Sky Forme,Grass Flying,600.0,100.0,103.0,75.0,120.0,75.0,127.0
586,493,Arceus,Normal,720.0,120.0,120.0,120.0,120.0,120.0,120.0

In [17]:
unq, count = np.unique(df.ID, axis=0, return_counts=True)

In [22]:
unq[count>1]

array([  3,   6,   9,  15,  18,  19,  20,  25,  26,  27,  28,  37,  38,
        50,  51,  52,  53,  65,  74,  75,  76,  77,  78,  79,  80,  83,
        88,  89,  94, 103, 105, 110, 115, 122, 127, 130, 133, 142, 150,
       181, 208, 212, 214, 222, 229, 248, 254, 257, 260, 263, 264, 282,
       302, 303, 306, 308, 310, 319, 323, 334, 351, 354, 359, 362, 373,
       376, 380, 381, 382, 383, 384, 386, 413, 428, 445, 448, 460, 475,
       479, 487, 492])

In [36]:
first_dup = df.duplicated(subset = 'ID', keep = False)

In [37]:
first_dup

0      False
1      False
2       True
3       True
4      False
       ...
582    False
583    False
584     True
585     True
586    False
Length: 587, dtype: bool

In [40]:
duplicated = df[first_dup]
duplicated

,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
2,3,Venusaur,Grass Poison,525.0,80.0,82.0,83.0,100.0,100.0,80.0
3,3,Venusaur Mega Venusaur,Grass Poison,625.0,80.0,100.0,123.0,122.0,120.0,80.0
6,6,Charizard,Fire Flying,534.0,78.0,84.0,78.0,109.0,85.0,100.0
7,6,Charizard Mega Charizard X,Fire Dragon,634.0,78.0,130.0,111.0,130.0,85.0,100.0
8,6,Charizard Mega Charizard Y,Fire Flying,634.0,78.0,104.0,78.0,159.0,115.0,100.0
...,...,...,...,...,...,...,...,...,...,...
570,479,Rotom Mow Rotom,Electric Grass,520.0,50.0,65.0,107.0,105.0,107.0,86.0
578,487,Giratina Altered Forme,Ghost Dragon,680.0,150.0,100.0,120.0,100.0,120.0,90.0
579,487,Giratina Origin Forme,Ghost Dragon,680.0,150.0,120.0,100.0,120.0,100.0,90.0
584,492,Shaymin Land Forme,Grass,600.0,100.0,100.0,100.0,100.0,100.0,100.0
585,492,Shaymin Sky Forme,Grass Flying,600.0,100.0,103.0,75.0,120.0,75.0,127.0

In [43]:
dup_2 = duplicated.duplicated(subset = 'ID', keep = 'first')

In [48]:
dup_3 = duplicated[dup_2]
dup_3

,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
3,3,Venusaur Mega Venusaur,Grass Poison,625.0,80.0,100.0,123.0,122.0,120.0,80.0
7,6,Charizard Mega Charizard X,Fire Dragon,634.0,78.0,130.0,111.0,130.0,85.0,100.0
8,6,Charizard Mega Charizard Y,Fire Flying,634.0,78.0,104.0,78.0,159.0,115.0,100.0
12,9,Blastoise Mega Blastoise,Water,630.0,79.0,103.0,120.0,135.0,115.0,78.0
19,15,Beedrill Mega Beedrill,Bug Poison,495.0,65.0,150.0,40.0,15.0,80.0,145.0
...,...,...,...,...,...,...,...,...,...,...
568,479,Rotom Frost Rotom,Electric Ice,520.0,50.0,65.0,107.0,105.0,107.0,86.0
569,479,Rotom Fan Rotom,Electric Flying,520.0,50.0,65.0,107.0,105.0,107.0,86.0
570,479,Rotom Mow Rotom,Electric Grass,520.0,50.0,65.0,107.0,105.0,107.0,86.0
579,487,Giratina Origin Forme,Ghost Dragon,680.0,150.0,120.0,100.0,120.0,100.0,90.0
585,492,Shaymin Sky Forme,Grass Flying,600.0,100.0,103.0,75.0,120.0,75.0,127.0

In [53]:
idx = list(dup_3.index)

In [67]:
# Move these to the bottom of a main DF 
later_gen = df.loc[idx, :]
later_gen

,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
3,3,Venusaur Mega Venusaur,Grass Poison,625.0,80.0,100.0,123.0,122.0,120.0,80.0
7,6,Charizard Mega Charizard X,Fire Dragon,634.0,78.0,130.0,111.0,130.0,85.0,100.0
8,6,Charizard Mega Charizard Y,Fire Flying,634.0,78.0,104.0,78.0,159.0,115.0,100.0
12,9,Blastoise Mega Blastoise,Water,630.0,79.0,103.0,120.0,135.0,115.0,78.0
19,15,Beedrill Mega Beedrill,Bug Poison,495.0,65.0,150.0,40.0,15.0,80.0,145.0
...,...,...,...,...,...,...,...,...,...,...
568,479,Rotom Frost Rotom,Electric Ice,520.0,50.0,65.0,107.0,105.0,107.0,86.0
569,479,Rotom Fan Rotom,Electric Flying,520.0,50.0,65.0,107.0,105.0,107.0,86.0
570,479,Rotom Mow Rotom,Electric Grass,520.0,50.0,65.0,107.0,105.0,107.0,86.0
579,487,Giratina Origin Forme,Ghost Dragon,680.0,150.0,120.0,100.0,120.0,100.0,90.0
585,492,Shaymin Sky Forme,Grass Flying,600.0,100.0,103.0,75.0,120.0,75.0,127.0

In [68]:
early_gen = df.loc[idx, :]

In [69]:
df

,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
0,1,Bulbasaur,Grass Poison,318.0,45.0,49.0,49.0,65.0,65.0,45.0
1,2,Ivysaur,Grass Poison,405.0,60.0,62.0,63.0,80.0,80.0,60.0
2,3,Venusaur,Grass Poison,525.0,80.0,82.0,83.0,100.0,100.0,80.0
3,3,Venusaur Mega Venusaur,Grass Poison,625.0,80.0,100.0,123.0,122.0,120.0,80.0
4,4,Charmander,Fire,309.0,39.0,52.0,43.0,60.0,50.0,65.0
...,...,...,...,...,...,...,...,...,...,...
582,490,Manaphy,Water,600.0,100.0,100.0,100.0,100.0,100.0,100.0
583,491,Darkrai,Dark,600.0,70.0,90.0,90.0,135.0,90.0,125.0
584,492,Shaymin Land Forme,Grass,600.0,100.0,100.0,100.0,100.0,100.0,100.0
585,492,Shaymin Sky Forme,Grass Flying,600.0,100.0,103.0,75.0,120.0,75.0,127.0
586,493,Arceus,Normal,720.0,120.0,120.0,120.0,120.0,120.0,120.0

In [105]:
mega = df[df['NAME'].str.contains('Mega ')]
mega

,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
3,3,Venusaur Mega Venusaur,Grass Poison,625.0,80.0,100.0,123.0,122.0,120.0,80.0
7,6,Charizard Mega Charizard X,Fire Dragon,634.0,78.0,130.0,111.0,130.0,85.0,100.0
8,6,Charizard Mega Charizard Y,Fire Flying,634.0,78.0,104.0,78.0,159.0,115.0,100.0
12,9,Blastoise Mega Blastoise,Water,630.0,79.0,103.0,120.0,135.0,115.0,78.0
19,15,Beedrill Mega Beedrill,Bug Poison,495.0,65.0,150.0,40.0,15.0,80.0,145.0
23,18,Pidgeot Mega Pidgeot,Normal Flying,579.0,83.0,80.0,80.0,135.0,80.0,121.0
84,65,Alakazam Mega Alakazam,Psychic,600.0,55.0,50.0,65.0,175.0,105.0,150.0
106,80,Slowbro Mega Slowbro,Water Psychic,590.0,95.0,75.0,180.0,130.0,80.0,30.0
125,94,Gengar Mega Gengar,Ghost Poison,600.0,60.0,65.0,80.0,170.0,95.0,130.0
150,115,Kangaskhan Mega Kangaskhan,Normal,590.0,105.0,125.0,100.0,60.0,100.0,100.0
164,127,Pinsir Mega Pinsir,Bug Flying,600.0,65.0,155.0,120.0,65.0,90.0,105.0
168,130,Gyarados Mega Gyarados,Water Dark,640.0,95.0,155.0,109.0,70.0,130.0,81.0
182,142,Aerodactyl Mega Aerodactyl,Rock Flying,615.0,80.0,135.0,85.0,70.0,95.0,150.0
191,150,Mewtwo Mega Mewtwo X,Psychic Fighting,780.0,106.0,190.0,100.0,154.0,100.0,130.0
192,150,Mewtwo Mega Mewtwo Y,Psychic,780.0,106.0,150.0,70.0,194.0,120.0,140.0
224,181,Ampharos Mega Ampharos,Electric Dragon,610.0,90.0,95.0,105.0,165.0,110.0,45.0
252,208,Steelix Mega Steelix,Steel Ground,610.0,75.0,125.0,230.0,55.0,95.0,30.0
257,212,Scizor Mega Scizor,Bug Steel,600.0,70.0,150.0,140.0,65.0,100.0,75.0
260,214,Heracross Mega Heracross,Bug Fighting,600.0,80.0,185.0,115.0,40.0,105.0,75.0
277,229,Houndoom Mega Houndoom,Dark Fire,600.0,75.0,90.0,90.0,140.0,90.0,115.0
297,248,Tyranitar Mega Tyranitar,Rock Dark,700.0,100.0,164.0,150.0,95.0,120.0,71.0
304,254,Sceptile Mega Sceptile,Grass Dragon,630.0,70.0,110.0,75.0,145.0,85.0,145.0
308,257,Blaziken Mega Blaziken,Fire Fighting,630.0,80.0,160.0,80.0,130.0,80.0,100.0
312,260,Swampert Mega Swampert,Water Ground,635.0,100.0,150.0,110.0,95.0,110.0,70.0
337,282,Gardevoir Mega Gardevoir,Psychic Fairy,618.0,68.0,85.0,65.0,165.0,135.0,100.0
358,302,Sableye Mega Sableye,Dark Ghost,480.0,50.0,85.0,125.0,85.0,115.0,20.0
360,303,Mawile Mega Mawile,Steel Fairy,480.0,50.0,105.0,125.0,55.0,95.0,50.0
364,306,Aggron Mega Aggron,Steel,630.0,70.0,140.0,230.0,60.0,80.0,50.0
367,308,Medicham Mega Medicham,Fighting Psychic,510.0,60.0,100.0,85.0,80.0,85.0,100.0
370,310,Manectric Mega Manectric,Electric,575.0,70.0,75.0,80.0,135.0,80.0,135.0
380,319,Sharpedo Mega Sharpedo,Water Dark,560.0,70.0,140.0,70.0,110.0,65.0,105.0
385,323,Camerupt Mega Camerupt,Fire Ground,560.0,70.0,120.0,100.0,145.0,105.0,20.0
397,334,Altaria Mega Altaria,Dragon Fairy,590.0,75.0,110.0,110.0,110.0,105.0,80.0
421,354,Banette Mega Banette,Ghost,555.0,64.0,165.0,75.0,93.0,83.0,75.0
427,359,Absol Mega Absol,Dark,565.0,65.0,150.0,60.0,115.0,60.0,115.0
431,362,Glalie Mega Glalie,Ice,580.0,80.0,120.0,80.0,120.0,80.0,100.0
443,373,Salamence Mega Salamence,Dragon Flying,700.0,95.0,145.0,130.0,120.0,90.0,120.0
447,376,Metagross Mega Metagross,Steel Psychic,700.0,80.0,145.0,150.0,105.0,110.0,110.0
452,380,Latias Mega Latias,Dragon Psychic,700.0,80.0,100.0,120.0,140.0,150.0,110.0
454,381,Latios Mega Latios,Dragon Psychic,700.0,80.0,130.0,100.0,160.0,120.0,110.0
460,384,Rayquaza Mega Rayquaza,Dragon Flying,780.0,105.0,180.0,100.0,180.0,100.0,115.0
510,428,Lopunny Mega Lopunny,Normal Fighting,580.0,65.0,136.0,94.0,54.0,96.0,135.0
528,445,Garchomp Mega Garchomp,Dragon Ground,700.0,108.0,170.0,115.0,120.0,95.0,92.0
532,448,Lucario Mega Lucario,Fighting Steel,625.0,70.0,145.0,88.0,140.0,70.0,112.0
545,460,Abomasnow Mega Abomasnow,Grass Ice,594.0,90.0,132.0,105.0,132.0,105.0,30.0
561,475,Gallade Mega Gallade,Psychic Fighting,618.0,68.0,165.0,95.0,65.0,115.0,110.0

In [83]:
idx = list(mega.index)

In [76]:
mega.to_csv("mega.csv", header = True)

In [77]:
pokemon = pd.read_csv('pokemon.csv', index_col = None)

In [79]:
pokemon = pokemon.drop('Unnamed: 0', axis = 1)

In [102]:
bad_df = pokemon.ID.isin(idx)

In [104]:
pokemon[~bad_df]

,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
0,1,Bulbasaur,Grass Poison,318.0,45.0,49.0,49.0,65.0,65.0,45.0
1,2,Ivysaur,Grass Poison,405.0,60.0,62.0,63.0,80.0,80.0,60.0
4,4,Charmander,Fire,309.0,39.0,52.0,43.0,60.0,50.0,65.0
5,5,Charmeleon,Fire,405.0,58.0,64.0,58.0,80.0,65.0,80.0
6,6,Charizard,Fire Flying,534.0,78.0,84.0,78.0,109.0,85.0,100.0
...,...,...,...,...,...,...,...,...,...,...
1040,896,Glastrier,Ice,580.0,100.0,145.0,130.0,65.0,110.0,30.0
1041,897,Spectrier,Ghost,580.0,100.0,65.0,60.0,145.0,80.0,130.0
1042,898,Calyrex,Psychic Grass,500.0,100.0,80.0,80.0,80.0,80.0,80.0
1043,898,Calyrex Ice Rider,Psychic Ice,680.0,100.0,165.0,150.0,85.0,130.0,50.0
1044,898,Calyrex Shadow Rider,Psychic Ghost,680.0,100.0,85.0,80.0,165.0,100.0,150.0

In [5]:
old_stat = pd.read_csv('old_gen_wdup.csv', index_col = None)

In [13]:
old_stat = old_stat.drop('Unnamed: 0', axis = 1)

In [14]:
galarian = old_stat[old_stat['NAME'].str.contains('Galarian ')]

In [15]:
galarian

,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
63,52,Meowth Galarian Meowth,Steel,290.0,50.0,65.0,55.0,40.0,40.0,40.0
93,77,Ponyta Galarian Ponyta,Psychic,410.0,50.0,85.0,55.0,65.0,65.0,90.0
95,78,Rapidash Galarian Rapidash,Psychic Fairy,500.0,65.0,100.0,70.0,80.0,80.0,105.0
97,79,Slowpoke Galarian Slowpoke,Psychic,315.0,90.0,65.0,65.0,40.0,40.0,15.0
99,80,Slowbro Galarian Slowbro,Poison Psychic,490.0,95.0,100.0,95.0,100.0,70.0,30.0
103,83,Farfetch'd Galarian Farfetch'd,Fighting,377.0,52.0,95.0,55.0,58.0,62.0,55.0
135,110,Weezing Galarian Weezing,Poison Fairy,490.0,65.0,90.0,120.0,85.0,70.0,60.0
148,122,Mr. Mime Galarian Mr. Mime,Psychic Ice,460.0,50.0,65.0,65.0,90.0,90.0,100.0
250,222,Corsola Galarian Corsola,Ghost,410.0,60.0,55.0,100.0,65.0,100.0,30.0
292,263,Zigzagoon Galarian Zigzagoon,Dark Normal,240.0,38.0,30.0,41.0,30.0,41.0,60.0
294,264,Linoone Galarian Linoone,Dark Normal,420.0,78.0,70.0,61.0,50.0,61.0,100.0

In [17]:
galarian_idx = galarian.index
galarian_idx

Int64Index([63, 93, 95, 97, 99, 103, 135, 148, 250, 292, 294], dtype='int64')

In [21]:
old_stat.index.isin(galarian_idx)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False,  True, False,  True, False,
        True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [23]:
old_stat_upd = old_stat[~old_stat.index.isin(galarian_idx)]

In [24]:
old_stat_upd

,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
0,1,Bulbasaur,Grass Poison,318.0,45.0,49.0,49.0,65.0,65.0,45.0
1,2,Ivysaur,Grass Poison,405.0,60.0,62.0,63.0,80.0,80.0,60.0
2,3,Venusaur,Grass Poison,525.0,80.0,82.0,83.0,100.0,100.0,80.0
3,4,Charmander,Fire,309.0,39.0,52.0,43.0,60.0,50.0,65.0
4,5,Charmeleon,Fire,405.0,58.0,64.0,58.0,80.0,65.0,80.0
...,...,...,...,...,...,...,...,...,...,...
536,490,Manaphy,Water,600.0,100.0,100.0,100.0,100.0,100.0,100.0
537,491,Darkrai,Dark,600.0,70.0,90.0,90.0,135.0,90.0,125.0
538,492,Shaymin Land Forme,Grass,600.0,100.0,100.0,100.0,100.0,100.0,100.0
539,492,Shaymin Sky Forme,Grass Flying,600.0,100.0,103.0,75.0,120.0,75.0,127.0
540,493,Arceus,Normal,720.0,120.0,120.0,120.0,120.0,120.0,120.0

In [25]:
old_stat_upd.to_csv("old_stat_upd.csv", header = True)

In [27]:
new_stat = pd.read_csv('new_gen.csv', index_col = None)

In [28]:
new_stat

,Unnamed: 0,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
0,545,457,Lumineon,Water,460.0,69.0,69.0,76.0,69.0,86.0,91.0
1,546,458,Mantyke,Water Flying,345.0,45.0,20.0,50.0,60.0,120.0,50.0
2,547,459,Snover,Grass Ice,334.0,60.0,62.0,50.0,62.0,60.0,40.0
3,548,460,Abomasnow,Grass Ice,494.0,90.0,92.0,75.0,92.0,85.0,60.0
4,549,460,Abomasnow Mega Abomasnow,Grass Ice,594.0,90.0,132.0,105.0,132.0,105.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...
495,1040,896,Glastrier,Ice,580.0,100.0,145.0,130.0,65.0,110.0,30.0
496,1041,897,Spectrier,Ghost,580.0,100.0,65.0,60.0,145.0,80.0,130.0
497,1042,898,Calyrex,Psychic Grass,500.0,100.0,80.0,80.0,80.0,80.0,80.0
498,1043,898,Calyrex Ice Rider,Psychic Ice,680.0,100.0,165.0,150.0,85.0,130.0,50.0
499,1044,898,Calyrex Shadow Rider,Psychic Ghost,680.0,100.0,85.0,80.0,165.0,100.0,150.0

In [31]:
main_df = pd.read_csv('main_df.csv', index_col = None)

In [32]:
main_df

,Unnamed: 0,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
0,0,1,Bulbasaur,Grass Poison,318.0,45.0,49.0,49.0,65.0,65.0,45.0
1,1,2,Ivysaur,Grass Poison,405.0,60.0,62.0,63.0,80.0,80.0,60.0
2,2,3,Venusaur,Grass Poison,525.0,80.0,82.0,83.0,100.0,100.0,80.0
3,3,4,Charmander,Fire,309.0,39.0,52.0,43.0,60.0,50.0,65.0
4,4,5,Charmeleon,Fire,405.0,58.0,64.0,58.0,80.0,65.0,80.0
...,...,...,...,...,...,...,...,...,...,...,...
988,988,896,Glastrier,Ice,580.0,100.0,145.0,130.0,65.0,110.0,30.0
989,989,897,Spectrier,Ghost,580.0,100.0,65.0,60.0,145.0,80.0,130.0
990,990,898,Calyrex,Psychic Grass,500.0,100.0,80.0,80.0,80.0,80.0,80.0
991,991,898,Calyrex Ice Rider,Psychic Ice,680.0,100.0,165.0,150.0,85.0,130.0,50.0
992,992,898,Calyrex Shadow Rider,Psychic Ghost,680.0,100.0,85.0,80.0,165.0,100.0,150.0

In [34]:
main_df = main_df.drop("Unnamed: 0", axis =1)

In [35]:
df1 = main_df[:541]

In [36]:
df1

,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
0,1,Bulbasaur,Grass Poison,318.0,45.0,49.0,49.0,65.0,65.0,45.0
1,2,Ivysaur,Grass Poison,405.0,60.0,62.0,63.0,80.0,80.0,60.0
2,3,Venusaur,Grass Poison,525.0,80.0,82.0,83.0,100.0,100.0,80.0
3,4,Charmander,Fire,309.0,39.0,52.0,43.0,60.0,50.0,65.0
4,5,Charmeleon,Fire,405.0,58.0,64.0,58.0,80.0,65.0,80.0
...,...,...,...,...,...,...,...,...,...,...
536,490,Manaphy,Water,600.0,100.0,100.0,100.0,100.0,100.0,100.0
537,491,Darkrai,Dark,600.0,70.0,90.0,90.0,135.0,90.0,125.0
538,492,Shaymin Land Forme,Grass,600.0,100.0,100.0,100.0,100.0,100.0,100.0
539,492,Shaymin Sky Forme,Grass Flying,600.0,100.0,103.0,75.0,120.0,75.0,127.0
540,493,Arceus,Normal,720.0,120.0,120.0,120.0,120.0,120.0,120.0

In [37]:
df2 = main_df[541:]

In [38]:
df2

,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
541,494,Victini,Psychic Fire,600.0,100.0,100.0,100.0,100.0,100.0,100.0
542,495,Snivy,Grass,308.0,45.0,45.0,55.0,45.0,55.0,63.0
543,496,Servine,Grass,413.0,60.0,60.0,75.0,60.0,75.0,83.0
544,497,Serperior,Grass,528.0,75.0,75.0,95.0,75.0,95.0,113.0
545,498,Tepig,Fire,308.0,65.0,63.0,45.0,45.0,45.0,45.0
...,...,...,...,...,...,...,...,...,...,...
988,896,Glastrier,Ice,580.0,100.0,145.0,130.0,65.0,110.0,30.0
989,897,Spectrier,Ghost,580.0,100.0,65.0,60.0,145.0,80.0,130.0
990,898,Calyrex,Psychic Grass,500.0,100.0,80.0,80.0,80.0,80.0,80.0
991,898,Calyrex Ice Rider,Psychic Ice,680.0,100.0,165.0,150.0,85.0,130.0,50.0
992,898,Calyrex Shadow Rider,Psychic Ghost,680.0,100.0,85.0,80.0,165.0,100.0,150.0

In [45]:
df2 = pd.concat([df2,galarian])

In [46]:
df2

,ID,NAME,TYPE,BASE STAT,HP,ATTACK,DEFENSE,SP ATTACK,SP DEFENSE,SPEED
541,494,Victini,Psychic Fire,600.0,100.0,100.0,100.0,100.0,100.0,100.0
542,495,Snivy,Grass,308.0,45.0,45.0,55.0,45.0,55.0,63.0
543,496,Servine,Grass,413.0,60.0,60.0,75.0,60.0,75.0,83.0
544,497,Serperior,Grass,528.0,75.0,75.0,95.0,75.0,95.0,113.0
545,498,Tepig,Fire,308.0,65.0,63.0,45.0,45.0,45.0,45.0
...,...,...,...,...,...,...,...,...,...,...
135,110,Weezing Galarian Weezing,Poison Fairy,490.0,65.0,90.0,120.0,85.0,70.0,60.0
148,122,Mr. Mime Galarian Mr. Mime,Psychic Ice,460.0,50.0,65.0,65.0,90.0,90.0,100.0
250,222,Corsola Galarian Corsola,Ghost,410.0,60.0,55.0,100.0,65.0,100.0,30.0
292,263,Zigzagoon Galarian Zigzagoon,Dark Normal,240.0,38.0,30.0,41.0,30.0,41.0,60.0
294,264,Linoone Galarian Linoone,Dark Normal,420.0,78.0,70.0,61.0,50.0,61.0,100.0

In [47]:
df2.to_csv("new_stat_upd.csv", header = True)

In [51]:
base_old = list(old_stat_upd['BASE STAT'])
base_new = list(df2['BASE STAT'])

In [52]:
outliers=[]
def detect_outlier(data_1):
    
    threshold=3
    mean_1 = np.mean(data_1)
    std_1 =np.std(data_1)
    
    
    for y in data_1:
        z_score= (y - mean_1)/std_1 
        if np.abs(z_score) > threshold:
            outliers.append(y)
    return outliers

In [53]:
detect_outlier(base_old)

[770.0, 770.0]

In [54]:
detect_outlier(base_new)

[770.0, 770.0, 1125.0]

In [55]:
base_new.remove(1125.0)

In [56]:
def welch_test_statistic(sample_1, sample_2):
    numerator = np.mean(sample_1) - np.mean(sample_2)
    denominator_sq = (np.var(sample_1) / len(sample_1)) + \
                        (np.var(sample_2) / len(sample_2))
    return numerator / np.sqrt(denominator_sq)

In [57]:
test_statistic = welch_test_statistic(base_old, base_new)
print("Welch Test Statistic: {:2.2f}".format(test_statistic))

Welch Test Statistic: -3.27

In [58]:
def welch_df(sample_1, sample_2):
    ss1 = len(sample_1)
    ss2 = len(sample_2)
    df = (
        ((np.var(sample_1)/ss1 + np.var(sample_2)/ss2)**(2.0)) / 
        ((np.var(sample_1)/ss1)**(2.0)/(ss1 - 1) + (np.var(sample_2)/ss2)**(2.0)/(ss2 - 1))
    )
    return df

In [60]:
dof = welch_df(base_old, base_new)
print("Degrees of Freedom for Welch's Test: {:2.2f}".format(dof))

Degrees of Freedom for Welch's Test: 964.89

In [61]:
from scipy import stats
# T-distribution
students = stats.t(dof)
pvalue = students.cdf(test_statistic) + (1 - students.cdf(-test_statistic))
print("p-value for different average total stats: {:2.9f}".format(pvalue))

p-value for different average total stats: 0.001125976